import { createRequire } from 'node:module';
import { mkdirSync } from 'node:fs';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'C:/Users/Hi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({headless:true,args:['--autoplay-policy=no-user-gesture-required']});
const errors=[];
mkdirSync('qa',{recursive:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']});
const page=await context.newPage();
page.on('pageerror',error=>errors.push(error.message));
const visible=id=>page.locator(`[data-window="${id}"][data-visible="true"]`);
async function settle(){await page.waitForTimeout(800);}
try {
  await page.goto('http://localhost:5173');
  await page.getByRole('button',{name:'Skip intro'}).click();
  await page.waitForSelector('.boot',{state:'detached'});
  await settle();
  assert.equal(await visible('about').count(),1);
  await page.screenshot({path:'qa/desktop-about.png'});
  await page.locator('[data-task="projects"]').click();await settle();
  assert.equal(await visible('about').count(),0);
  await page.getByRole('button',{name:/Personal Desktop/}).click();
  await page.getByRole('heading',{name:'Personal Desktop',exact:true}).waitFor();
  await page.getByRole('button',{name:'Back to projects'}).click();
  await page.getByRole('heading',{name:"Things I've been building."}).waitFor();
  await page.screenshot({path:'qa/desktop-projects.png'});
  await page.locator('[data-task="about"]').click();await settle();
  await page.mouse.move(1200,800);await page.mouse.wheel(0,170);await settle();
  assert.equal(await page.locator('main').getAttribute('data-section'),'projects');
  await page.mouse.wheel(0,170);await settle();
  assert.equal(await page.locator('main').getAttribute('data-story-complete'),'true');
  await page.getByRole('button',{name:'Copy email',exact:true}).click();
  assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'QuocDung.Pham@UTDallas.edu');
  await page.screenshot({path:'qa/desktop-contact.png'});
  await page.locator('[data-task="contact"]').click();await settle();
  assert.equal(await visible('contact').count(),0);
  await page.locator('[data-task="contact"]').click();await settle();
  assert.equal(await visible('contact').count(),1);
  const corner=page.getByRole('button',{name:'Spin contact-me.txt - Address Book from bottom-right corner'});
  const box=await corner.boundingBox();
  await page.mouse.move(box.x+5,box.y+5);await page.mouse.down();await page.mouse.move(box.x-95,box.y-55,{steps:10});await settle();
  const spun=await visible('contact').evaluate(el=>getComputedStyle(el).transform);
  assert.notEqual(spun,'none');
  await page.screenshot({path:'qa/window-spin.png'});
  await page.mouse.up();await settle();
  const resetTransform=await visible('contact').evaluate(el=>getComputedStyle(el).transform);
  assert.ok(resetTransform==='none'||resetTransform==='matrix(1, 0, 0, 1, 0, 0)',resetTransform);
  await page.getByRole('button',{name:'Maximize contact-me.txt - Address Book'}).click();
  assert.ok(await visible('contact').evaluate(el=>el.classList.contains('maximized')));
  await page.getByRole('button',{name:'Restore contact-me.txt - Address Book'}).click();
  await page.getByRole('button',{name:'Start menu'}).click();
  await page.getByRole('menuitem',{name:'Reset desktop'}).click();await settle();
  assert.equal(await page.locator('main').getAttribute('data-story-complete'),'false');
  const phone=await context.newPage();
  await phone.setViewportSize({width:390,height:844});
  await phone.emulateMedia({reducedMotion:'reduce'});
  phone.on('pageerror',error=>errors.push(error.message));
  await phone.goto('http://localhost:5173');await phone.waitForSelector('.boot',{state:'detached'});await settle();
  for(const id of ['about','projects','contact']) {
    await phone.locator(`[data-task="${id}"]`).click();await phone.waitForTimeout(150);
    await phone.screenshot({path:`qa/mobile-${id}.png`});
    const metrics=await phone.locator(`[data-window="${id}"]`).evaluate(el=>{const r=el.getBoundingClientRect();return {left:r.left,right:r.right,bottom:r.bottom,width:window.innerWidth,bar:document.querySelector('.taskbar').getBoundingClientRect().top,overflow:document.documentElement.scrollWidth>window.innerWidth};});
    assert.ok(metrics.left>=0&&metrics.right<=metrics.width&&!metrics.overflow,JSON.stringify(metrics));
    assert.ok(metrics.bottom<=metrics.bar,JSON.stringify(metrics));
  }
  assert.equal(await phone.locator('.ambient canvas').count(),0);
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({passed:true,checks:['boot skip','taskbar navigation','project detail/back','scroll advances','end-of-story toggles','copy email','corner spin/click-off reset','maximize/restore','start reset','mobile layout','reduced-motion fallback'],screenshots:'qa/'}));
} finally {await browser.close();}
